[package]
name = "country_loader"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
path = "src/main.rs"

[[bin]]
name = "country_loader"
path = "src/main.rs"

[dependencies]
landly-server.workspace = true
country_parser.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
dotenv.workspace = true