[package]
name = "country_parser"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
path = "src/main.rs"

[[bin]]
name = "country_parser"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
